# Generated by Django 5.1.6 on 2025-02-15 08:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('website', models.URLField(blank=True)),
                ('founded_date', models.DateField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, upload_to='company_logos/')),
                ('description', models.TextField(blank=True)),
                ('number_of_employees', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=100)),
                ('salrange', models.IntegerField()),
                ('cat', models.CharField(max_length=100)),
                ('jdetails', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('application_deadline', models.DateTimeField()),
                ('contact_email', models.EmailField(max_length=100)),
                ('contact_phone', models.CharField(max_length=15)),
                ('job_type', models.CharField(max_length=50)),
                ('experience_required', models.CharField(max_length=100)),
                ('job_summary', models.TextField()),
                ('required_skills', models.TextField()),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='japp.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium_start_date', models.DateField(auto_now_add=True)),
                ('premium_end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserJobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Interview Scheduled', 'Interview Scheduled'), ('Offered', 'Offered'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('cover_letter', models.TextField(blank=True)),
                ('resume', models.FileField(blank=True, upload_to='applications/resumes/')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='japp.companyprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='japp.jobs')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Phone number must be entered in the format: "+999999999".')])),
                ('address', models.CharField(blank=True, max_length=255)),
                ('dob', models.DateField(blank=True, null=True)),
                ('education', models.TextField(blank=True)),
                ('work_experience', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics/')),
                ('resume', models.FileField(blank=True, upload_to='resumes/')),
                ('user', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
