# Generated by Django 5.1.6 on 2025-02-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japp', '0002_rename_premium_premiums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/user_m2pACW0.png', upload_to='profile_pics/'),
        ),
    ]
